Algoritmo "Lista 01 - Exercício 04"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Calcula a área de um Círculo.
// Autor(a)    : Higor Rocha
// Data atual  : 05/08/2024
Var
r, cac:real

Inicio
// Entrada
escreva("Informe o Valor de R: ")
leia(r)

// Processamento
cac <- r*r

// Saída
escreva("A área do círculo é: ", cac*3.1416:1:2)

Fimalgoritmo