Algoritmo "Lista 01 - Exercício 06"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Calcula o volume de um Círculo.
// Autor(a)    : Higor Rocha
// Data atual  : 05/08/2024
Var
r, h, cvc:real

Inicio
// Entrada
escreva("Informe o Valor de R: ")
leia(r)
escreva("Informe o Valor de H: ")
leia(h)

// Processamento
cvc <- (r*r)*h

// Saída
escreva("O volume do círculo é: ", cvc*3.1416:1:2)

Fimalgoritmo