Algoritmo "Lista 01 - Exercício 18"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Recebe um número inteiro e diz o resto da divisão por 2
// Autor(a)    : Higor Rocha
// Data atual  : 05/08/2024
Var
num, resto: real

Inicio
// Entrada
escreva("Digite um número inteiro: ")
leia(num)

// Processamento
resto <- num % 2

// Saída
escreva("O resto da divisão por 2 é: ", resto:1)

Fimalgoritmo