Algoritmo "Lista 01 - Exercício 03"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Calcula a área de um triângulo.
// Autor(a)    : Higor Rocha
// Data atual  : 05/08/2024
Var
area, base, altura:real

Inicio
// Entrada
escreva("Digite o Valor da Base: ")
leia(base)
escreva("Digite o Valor da Altura: ")
leia(altura)

// Saída
escreva("A área do triângulo é: ", (base*altura)/2:1:2)

Fimalgoritmo