Algoritmo "Lista 04 - Exercício 22"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Solicita uma palavra e apresenta em maiúsculo.
// Autor(a)    : Higor Rocha Alves
// Data atual  : 27/08/2024
Var
   palavra: caractere

Inicio
      // Entrada
      escreva("Digite uma palavra: ")
      leia(palavra)
      
      // Saída
      escreva("A palavra é: ", maiusc(palavra))

Fimalgoritmo