Algoritmo "Lista 04 - Exercício 01"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Solicita uma palavra e informa a quantidade de caracteres.
// Autor(a)    : Higor Rocha Alves
// Data atual  : 27/08/2024
Var
   palavra: caractere

Inicio
      // Entrada
      escreva("Digite uma palavra entre 4 e 30 caracteres: ")
      leia(palavra)
      
      // Saída
      escreva("A palavra contém ",compr(palavra):1," caracteres:")

Fimalgoritmo