Algoritmo "Lista 03 - Exercício 04"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Apresenta os números de 5 a 20 na tela.(Linha a Linha)
// Autor(a)    : Higor Rocha Alves
// Data atual  : 15/08/2024
Var
num: inteiro

Inicio
// Entrada e Processamento
para num de 5 ate 20 faca
     escreval("Número ",num:1)
fimpara

Fimalgoritmo