Algoritmo "Lista 01 - Exercício 05"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Calcula o perímetro de um Círculo.
// Autor(a)    : Higor Rocha
// Data atual  : 05/08/2024
Var
r, cpc:real

Inicio
// Entrada
escreva("Informe o Valor de R: ")
leia(r)

// Processamento
cpc <- r+r

// Saída
escreva("O perímetro do círculo é: ", cpc*3.1416:1:2)

Fimalgoritmo