Algoritmo "Lista 01 - Exercício 02"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Recebe e soma dois números
// Autor(a)    : Higor Rocha
// Data atual  : 05/08/2024
Var
num_1, num_2:real

Inicio
// Entrada
escreva("Digita o Primeiro Número: ")
leia(num_1)
escreva("Digite o Segundo Número: ")
leia(num_2)

// Saída
escreva("A soma dos dois números é: ",num_1+num_2:1)

Fimalgoritmo