Algoritmo "Lista 02 - Exercício 12"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Descrição   : Solicita um número e diz se é Par ou Ímpar.
// Autor(a)    : Higor Rocha Alves
// Data atual  : 13/08/2024
Var
num:inteiro

Inicio
// Entrada
escreva("Insira um número: ")
leia(num)

// Saída
se num % 2 = 0 entao
   escreva("Número par!")
 senao
      escreva("Número ímpar!")
fimse

Fimalgoritmo