Algoritmo "Lista 06 - Exercício 02"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : Alexandre Moreno 
// Autor(a)    : Higor Rocha
// Data atual  : 16/10/2024
Var
   num: vetor [1..21] de inteiro
   i: inteiro
Inicio
      para i de 1 ate 21 faca
           escreva("Digite o ",i,"º Número: ")
           leia(num[i])
      fimpara
      para i de 21 ate 1 passo -1 faca
           escreval("Número: ",num[i]:1)
      fimpara
      
Fimalgoritmo